---
title: "Final Model"
author: "Jack Schroeder"
date: "10/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(geofacet)
library(gt)
library(lubridate)
library(randomForest)
library(caret)
library(statebins)

# Need:

# Formula
# Justification
# Coefficients/weights
# Justify these
# Model validation
# Uncertainty
# Graphics

```

```{r historical data, include=FALSE}

# Results by state

votedata <- read_csv("../Data/popvote_bystate_1948-2016.csv")

# Take COVI and use it for turnout draw?

vep <- read_csv("../Data/vep_1980-2016.csv") %>%
  mutate(state = case_when(state == "United States" ~ "National",
                           TRUE ~ state))

# Abandon prediction market - too much data to get, probably VERY correlated w/538 averages

# Instead I'll go with polling averages from 538. Should be workable.

names <- read_csv("../Data/pollavg_1968-2016.csv") %>% 
  select(year, party, candidate_name)

names <- distinct(names)

incumbent_d <- read_csv("../Data/popvote_1948-2016.csv") %>% 
  select(-c(candidate, pv)) %>% 
  filter(party == "democrat") %>% 
  mutate(my_us_pv2p_lag = lag(pv2p, order_by = year))

incumbent <- read_csv("../Data/popvote_1948-2016.csv") %>% 
  select(-c(candidate, pv)) %>% 
  filter(party == "republican") %>% 
  mutate(my_us_pv2p_lag = lag(pv2p, order_by = year)) %>% 
  rbind(., incumbent_d)

# Economic data by state - made this earlier, sticking with it w/o total cost/polls

econ <- read_csv("../Data/model_input_local.csv") %>% 
  select(-c(avg_support_10, avg_support_2, total_cost, D, R, total, pv, pv2p, incumbent, incumbent_party, prev_admin, term.x, term.y, winner, swing_r, swing_d, margin_pct_nat, margin_pct_lag_nat, swing_nat, pv2p_lag, R_pv2p, D_pv2p))

# Ad data - commenting out given how bad they were 

# ads <- read_csv("../Data/ad_campaigns_2000-2012.csv") %>% 
#   filter(after_primary > 0) %>% 
#   group_by(cycle, state, party) %>% 
#   summarize(ad_spend = sum(total_cost))
# 
# ads

# Approval

app <- read_csv("../Data/approval_gallup_1941-2020.csv") %>% 
  mutate(poll_enddate = as.Date(poll_enddate, "%m/%d/%Y"),
         poll_startdate = as.Date(poll_startdate, "%m/%d/%Y"),
         year = year(poll_enddate),
         month = month(poll_enddate),
         startmonth = month(poll_startdate),
         day = day(poll_enddate)) %>% 
  filter(year %% 4 == 0,
         month < 11) %>% 
  group_by(year) %>% 
  summarize(pres_app = mean(approve))

# EC

elec <- read_csv("../Data/electoralcollegevotes_1948-2020.csv")%>% 
  rename(state = X1) %>% 
  select(-c(X22, X23, X24, X25, X26, X27, X28)) %>% 
  filter(!is.na(state))

polls_2 <- read_csv("../Data/pres_pollaverages_1968-2016.csv") %>% 
  select(cycle, state, modeldate, candidate_name, pct_estimate, pct_trend_adjusted, election_date) %>% 
  rename(year = cycle) %>% 
  mutate(modeldate = as.Date(modeldate, "%m/%d/%Y"),
         election_date = as.Date(election_date, "%m/%d/%Y"),
         days_to = difftime(election_date, modeldate, unit="days")) %>% 
  filter(days_to < 15) %>% 
  group_by(year, state, candidate_name) %>% 
  summarize(avg_support_2 = mean(pct_estimate),
            avg_support_adjusted_2 = mean(pct_trend_adjusted))

polls_10 <- read_csv("../Data/pres_pollaverages_1968-2016.csv") %>% 
  select(cycle, state, modeldate, candidate_name, pct_estimate, pct_trend_adjusted, election_date) %>% 
  rename(year = cycle) %>% 
  mutate(modeldate = as.Date(modeldate, "%m/%d/%Y"),
         election_date = as.Date(election_date, "%m/%d/%Y"),
         days_to = difftime(election_date, modeldate, unit="days")) %>% 
  filter(days_to < 71 & days_to > 14) %>% 
  group_by(year, state, candidate_name) %>% 
  summarize(avg_support_10 = mean(pct_estimate),
            avg_support_adjusted_10 = mean(pct_trend_adjusted))

consolidated <- left_join(polls_2, polls_10, by = c("year", "state", "candidate_name")) %>% 
  left_join(., names, by = c("year", "candidate_name")) %>% 
  left_join(., incumbent, by = c("year", "party")) %>% 
  left_join(., votedata, by = c("year", "state")) %>% 
  left_join(., app, by = c("year")) %>% 
  left_join(., econ, by = c("year", "state", "party")) %>% 
  left_join(., vep, by = c("year", "state")) %>% 
  mutate(my_pv2p = case_when(party == "republican" ~ R_pv2p,
                             party == "democrat" ~ D_pv2p),
         my_pv2p_lag = case_when(party == "republican" ~ R_pv2p_lag,
                                 party == "democrat" ~ D_pv2p_lag)) %>% 
  filter(state != "National",
         state != "ME-1",
         state != "ME-2",
         state != "NE-1",
         state != "NE-2",
         state != "NE-3",
         !is.na(party)) %>% 
  select(-c(avg_support_2, avg_support_10))

#model1 <- lm(my_pv2p ~ avg_support_2 + avg_support_10 + my_pv2p_lag + pres_app + incumbent_party + GDP_growth_a + unemployment_loc_a, consolidated)

# This must be the place

final_model <- lm(my_pv2p ~ avg_support_adjusted_2 + avg_support_adjusted_10 + my_pv2p_lag + pres_app + incumbent_party + GDP_growth_a + unemployment_loc_a + my_us_pv2p_lag, consolidated)

# as_tibble(final_model$residuals) %>% 
#   mutate(sqe = value^2) %>% 
#   summarize(rmse = mean(sqe))

rmse_final_model <- sqrt(mean(final_model$residuals^2))

#AICtab(model1, final_model)

#summary(final_model)

consolidated$D_pv <- (consolidated$D / consolidated$total)*100
consolidated$R_pv <- (consolidated$R / consolidated$total)*100
consolidated$state_abb <- state.abb[match(consolidated$state, state.name)]
consolidated$state_abb[is.na(consolidated$state_abb)] <- "DC"

#summary(glm(my_pv2p/100 ~ avg_support_adjusted_2, consolidated, family = "binomial"))

#rmse(final_model)

```

```{r 2020 data, include=FALSE}

app_20 <- app %>% 
  filter(year == 2020)

vep_20 <- read_csv("../Data/vep_2020.csv") %>%
  mutate(state = case_when(state == "United States" ~ "National",
                           TRUE ~ state))

# Lagged voteshare

votes_20 <- read_csv("../Data/popvote_bystate_1948-2016.csv") %>% 
  filter(year == 2016) %>%
  rename(R_pv2p_16 = R_pv2p,
         D_pv2p_16 = D_pv2p) %>% 
  select(state, R_pv2p_16, D_pv2p_16)

state_u_20 <- read_csv("../Data/state_unemployment_2020.csv") %>% 
  select(State, Avg) %>% 
  rename(state = State, unemployment_loc_a = Avg)

state_u_20$state[state_u_20$state == "D.C."] <- "District of Columbia"

# Polls 2 week

polls_20_2 <- read_csv("../Data/presidential_poll_averages_2020.csv") %>% 
  select(cycle, state, modeldate, candidate_name, pct_estimate, pct_trend_adjusted) %>% 
  rename(year = cycle) %>% 
  mutate(modeldate = as.Date(modeldate, "%m/%d/%Y"),
         election_date = as.Date("11/03/2020", "%m/%d/%Y"),
         days_to = difftime(election_date, modeldate, unit="days")) %>% 
  filter(days_to < 15) %>% 
  group_by(year, state, candidate_name) %>% 
  summarize(avg_support_2 = mean(pct_estimate),
            avg_support_adjusted_2 = mean(pct_trend_adjusted))

# Polls 10 week

polls_20_10 <- read_csv("../Data/presidential_poll_averages_2020.csv") %>% 
  select(cycle, state, modeldate, candidate_name, pct_estimate, pct_trend_adjusted) %>% 
  rename(year = cycle) %>% 
  mutate(modeldate = as.Date(modeldate, "%m/%d/%Y"),
         election_date = as.Date("11/03/2020", "%m/%d/%Y"),
         days_to = difftime(election_date, modeldate, unit="days")) %>% 
  filter(days_to < 71 & days_to > 14) %>% 
  group_by(year, state, candidate_name) %>% 
  summarize(avg_support_10 = mean(pct_estimate),
            avg_support_adjusted_10 = mean(pct_trend_adjusted))

data_20 <-  left_join(polls_20_2, polls_20_10, by = c("year", "state", "candidate_name")) %>% 
  mutate(party = case_when(candidate_name == "Joseph R. Biden Jr." ~ "democrat",
                           candidate_name == "Donald Trump" ~ "republican",
                           TRUE ~ "Delete"),
         incumbent_party = case_when(candidate_name == "Joseph R. Biden Jr." ~ FALSE,
                           candidate_name == "Donald Trump" ~ TRUE),
         incumbent = case_when(candidate_name == "Joseph R. Biden Jr." ~ FALSE,
                           candidate_name == "Donald Trump" ~ TRUE)) %>% 
  filter(party != "Delete") %>% 
  left_join(., vep_20, by = c("state", "year")) %>% 
  left_join(., app_20, by = "year") %>% 
  left_join(., votes_20, by = "state") %>% 
  mutate(my_pv2p_lag = case_when(party == "democrat" ~ D_pv2p_16,
                                 party == "republican" ~ R_pv2p_16),
         unemployment_nat_t = 4.8,
         GDP_growth_a = -2.9,
         my_us_pv2p_lag = case_when(party == "democrat" ~ 51.16,
                                 party == "republican" ~ 48.83)) %>% 
  left_join(., state_u_20, by = "state") %>% 
  filter(state != "National",
         state != "ME-1",
         state != "ME-2",
         state != "NE-1",
         state != "NE-2",
         state != "NE-3",
         !is.na(party))

data_20$state_abb <- state.abb[match(data_20$state, state.name)]
data_20$state_abb[is.na(data_20$state_abb)] <- "DC"

# Lagged voteshare
# Take COVI and use it for turnout draw?
# Local econ
# National econ
# Approval data



```

```{r old models, echo=FALSE, cache=TRUE}
# state_glm_forecast <- list()
# state_glm_forecast_outputs <- data.frame()
# consolidated$state_abb <- state.abb[match(consolidated$state, state.name)]
# consolidated$state_abb[is.na(consolidated$state_abb)] <- "DC"
# for (s in unique(consolidated$state_abb)) {
#   
#   state_glm_forecast[[s]]$dat_D <- consolidated %>% 
#     filter(state_abb == s, party == "democrat")
#   state_glm_forecast[[s]]$mod_D <- glm(cbind(D, VEP - D) ~ avg_support_adjusted_10, 
#                                        state_glm_forecast[[s]]$dat_D,
#                                        family = binomial(link="logit"))
# 
#   state_glm_forecast[[s]]$dat_R <- consolidated %>% 
#     filter(state_abb == s, party == "republican")  
#   state_glm_forecast[[s]]$mod_R <- glm(cbind(R, VEP - R) ~ avg_support_adjusted_10, 
#                                        state_glm_forecast[[s]]$dat_R,
#                                        family = binomial(link="logit"))
#   
#   if (nrow(state_glm_forecast[[s]]$dat_R) > 2) {
#     for (hypo_avg_support_adjusted_10 in seq(from=0, to=100, by=10)) {
#       Dpred_voteprob <- predict(state_glm_forecast[[s]]$mod_D, 
#                                newdata=data.frame(avg_support_adjusted_10=hypo_avg_support_adjusted_10), se=T, type="response")
#       Dpred_q <- qt(0.975, df = df.residual(state_glm_forecast[[s]]$mod_D)) ## used in pred interval formula
#         
#       Rpred_voteprob <- predict(state_glm_forecast[[s]]$mod_R, 
#                                newdata=data.frame(avg_support_adjusted_10=hypo_avg_support_adjusted_10), se=T, type="response")
#       Rpred_q <- qt(0.975, df = df.residual(state_glm_forecast[[s]]$mod_R)) ## used in pred interval formula
# 
#       state_glm_forecast_outputs <- rbind(
#         state_glm_forecast_outputs,
#         cbind.data.frame(state = s, party = "democrat", x = hypo_avg_support_adjusted_10, 
#                          y = Dpred_voteprob$fit*100, 
#                          ymin = (Dpred_voteprob$fit - Rpred_q*Dpred_voteprob$se.fit)*100,
#                          ymax = (Dpred_voteprob$fit + Rpred_q*Dpred_voteprob$se.fit)*100),
#         cbind.data.frame(state = s, party = "republican", x = hypo_avg_support_adjusted_10, 
#                          y = Rpred_voteprob$fit*100, 
#                          ymin = (Rpred_voteprob$fit - Rpred_q*Rpred_voteprob$se.fit)*100,
#                          ymax = (Rpred_voteprob$fit + Rpred_q*Rpred_voteprob$se.fit)*100)
#       )
#     }
#   }
# }

# ggplot(state_glm_forecast_outputs, aes(x=x, y=y, ymin=ymin, ymax=ymax)) + 
#   facet_geo(~ state) +
#   geom_line(aes(color = party)) + 
#   geom_ribbon(aes(fill = party), alpha=0.5, color=NA) +
#   coord_cartesian(ylim=c(0, 100)) +
#   scale_color_manual(values = c("blue", "red")) +
#   scale_fill_manual(values = c("blue", "red")) +
#   xlab("hypothetical poll support") +
#   ylab('probability of state-eligible voter voting for party') +
#   theme_bw()
```

```{r state by state, echo=FALSE}

# # State by state.
# 
# ## Get relevant data
# VEP_TX_2020 <- as.integer(data_20$VEP[data_20$state_abb == "TX" & data_20$year == 2020])
# 
# TX_R <- consolidated %>% filter(state_abb=="TX", party=="republican")
# TX_D <- consolidated %>% filter(state_abb=="TX", party=="democrat")
# 
# ## Fit D and R models
# TX_R_glm <- glm(cbind(R, VEP-R) ~ avg_support_adjusted_2 + avg_support_adjusted_10 + my_pv2p_lag + incumbent_party, TX_R, family = binomial)
# TX_D_glm <- glm(cbind(D, VEP-D) ~ avg_support_adjusted_2 + avg_support_adjusted_10 + my_pv2p_lag + incumbent_party, TX_D, family = binomial)
# 
# ## Get predicted draw probabilities for D and R
# prob_Rvote_TX_2020 <- predict(TX_R_glm, newdata = data_20, subset = state_abb == "TX" & party == "republican", type="response")[[1]]
# prob_Dvote_TX_2020 <- predict(TX_D_glm, newdata = data_20, subset = state_abb == "TX" & party == "democrat", type="response")[[1]]
# 
# ## Get predicted distribution of draws from the population
# sim_Rvotes_TX_2020 <- rbinom(n = 10000, size = VEP_TX_2020, prob = prob_Rvote_TX_2020)
# sim_Dvotes_TX_2020 <- rbinom(n = 10000, size = VEP_TX_2020, prob = prob_Dvote_TX_2020)
# 
# ## Simulating a distribution of election results: Biden TX PV
# hist(sim_Dvotes_TX_2020, xlab="predicted turnout draws for Biden\nfrom 10,000 binomial process simulations", breaks=100)
# 
# ## Simulating a distribution of election results: Trump TX PV
# hist(sim_Rvotes_TX_2020, xlab="predicted turnout draws for Trump\nfrom 10,000 binomial process simulations", breaks=100)
# 
# ## Simulating a distribution of election results: Biden win margin
# sim_elxns_TX_2020 <- ((sim_Dvotes_TX_2020-sim_Rvotes_TX_2020)/(sim_Dvotes_TX_2020+sim_Rvotes_TX_2020))*100
# hist(sim_elxns_TX_2020, xlab="Biden Margin of Victory in TX")

# # Validation
# # State by state.
# 
# con_16 <- consolidated %>% 
#   filter(year == 2016)
# 
# con_16_minus <- consolidated %>% 
#   filter(year != 2016)
# 
# ## Get relevant data
# VEP_WI_2016 <- as.integer(con_16_minus$VEP[consolidated$state_abb == "WI"])
# 
# WI_R <- con_16_minus %>% filter(state_abb=="WI", party=="republican")
# WI_D <- con_16_minus %>% filter(state_abb=="WI", party=="democrat")
# 
# ## Fit D and R models
# WI_R_glm <- glm(cbind(R, VEP-R) ~ avg_support_adjusted_2 + avg_support_adjusted_10 + my_pv2p_lag + pres_app + incumbent_party + GDP_growth_a + unemployment_loc_a + my_us_pv2p_lag, WI_R, family = binomial)
# WI_D_glm <- glm(cbind(D, VEP-D) ~ avg_support_adjusted_2 + avg_support_adjusted_10 + my_pv2p_lag + pres_app + incumbent_party + GDP_growth_a + unemployment_loc_a + my_us_pv2p_lag, WI_D, family = binomial)
# 
# ## Get predicted draw probabilities for D and R
# prob_Rvote_WI_2016 <- predict(WI_R_glm, newdata = con_16, subset = state_abb == "WI" & party == "republican", type="response")[[1]]
# prob_Dvote_WI_2016 <- predict(WI_D_glm, newdata = con_16, subset = state_abb == "WI" & party == "democrat", type="response")[[1]]
# 
# ## Get predicted distribution of draws from the population
# sim_Rvotes_WI_2016 <- rbinom(n = 10000, size = VEP_WI_2016, prob = prob_Rvote_WI_2016)
# sim_Dvotes_WI_2016 <- rbinom(n = 10000, size = VEP_WI_2016, prob = prob_Dvote_WI_2016)
# 
# ## Simulating a distribution of election results: Biden WI PV
# hist(sim_Dvotes_WI_2016, xlab="predicted turnout draws for Biden\nfrom 10,000 binomial process simulations", breaks=100)
# 
# ## Simulating a distribution of election results: Trump WI PV
# hist(sim_Rvotes_WI_2016, xlab="predicted turnout draws for Trump\nfrom 10,000 binomial process simulations", breaks=100)
# 
# ## Simulating a distribution of election results: Biden win margin
# sim_elxns_WI_2016 <- ((sim_Dvotes_WI_2016-sim_Rvotes_WI_2016)/(sim_Dvotes_WI_2016+sim_Rvotes_WI_2016))*100
# hist(sim_elxns_WI_2016, xlab="Biden Margin of Victory in WI")
# 
# sqrt(mean(final_model$residuals)^2)
# 
# TX_D_1 <- TX_D %>% 
#   select(-c(state, year, party, candidate_name, candidate, state_abb))


```

```{r rf, echo=FALSE, cache=TRUE}

consolidated_omit <- na.omit(consolidated)

# Get rid of any possible problems with outcome variables being present in data.

model_data <- consolidated_omit %>% 
  select(-c(winner, pv2p, total, D, R, R_pv2p, D_pv2p, D_pv, R_pv, VEP, VAP))

set.seed(07901)
mrep <- train(my_pv2p ~ avg_support_adjusted_2 + avg_support_adjusted_10 + my_pv2p_lag + pres_app + incumbent_party + GDP_growth_a + unemployment_loc_a + my_us_pv2p_lag, model_data, subset = model_data$party == "republican", method = "ranger")

trump_20 <- data_20 %>% filter(party == "republican")
trump <- as_tibble(predict(mrep, trump_20))

set.seed(07901)
mdem <- train(my_pv2p ~ avg_support_adjusted_2 + avg_support_adjusted_10 + my_pv2p_lag + pres_app + incumbent_party + GDP_growth_a + unemployment_loc_a + my_us_pv2p_lag, model_data, subset = model_data$party == "democrat", method = "ranger")

biden_20 <- data_20 %>% filter(party == "democrat")
biden <- as_tibble(predict(mdem, biden_20))

states <- data_20 %>% 
  group_by(state) %>% 
  summarize(mean = mean(pres_app)) %>% 
  select(state)
states$rep <- trump$value
states$dem <- biden$value

results <- states %>% 
  mutate(R_pv2p = rep/(rep+dem),
         D_pv2p = dem/(rep+dem),
         winner = ifelse(R_pv2p > D_pv2p, "Trump", "Biden"),
         Guide = ifelse(R_pv2p > D_pv2p, ifelse(R_pv2p > 0.55, "Favor Trump", "Lean Trump"), ifelse(D_pv2p < 0.55, "Lean Biden", "Favor Biden")))

results %>% 
  ggplot(aes(fill = Guide, state=state)) +
  geom_statebins() +
  theme_statebins() +
  scale_fill_manual(values = c("#0000ff", "#add8e6", "#ffcccb", "#ff0000"),
                    breaks = c("Favor Biden", "Lean Biden", "Lean Trump", "Favor Trump")) +
  labs(title = "2020 Election Projection",
       subtitle = "Biden 334, Trump 204.",
       caption = "The underlying model is a random forest regression that includes various economic/polling indicators.\nRandom forests utilize decision trees with some predictors on some of the data to avoid overfitting.\nThe best of these trees are used together to predict future outcomes.\nModel and graphic created by Jack Schroeder.") +
  ggsave("../Plots/final_pv2p.png")

# EC tally

results %>% 
  left_join(., elec, by = "state") %>% 
  select(state, R_pv2p, D_pv2p, winner, Guide, `2020`) %>% 
  group_by(winner) %>% 
  tally(`2020`)

# Importance of variables - create natively

set.seed(07901)
mrep_rf <- randomForest(my_pv2p ~ avg_support_adjusted_2 + avg_support_adjusted_10 + my_pv2p_lag + pres_app + incumbent_party + GDP_growth_a + unemployment_loc_a + my_us_pv2p_lag, model_data, subset = model_data$party == "republican")

set.seed(07901)
mdem_rf <- randomForest(my_pv2p ~ avg_support_adjusted_2 + avg_support_adjusted_10 + my_pv2p_lag + pres_app + incumbent_party + GDP_growth_a + unemployment_loc_a + my_us_pv2p_lag, model_data, subset = model_data$party == "democrat", method = "ranger")

imp_rep <- as.data.frame(mdem_rf$importance) %>% 
  rename(Republican = IncNodePurity)
imp_dem <- as.data.frame(mrep_rf$importance) %>% 
  rename(Democrat = IncNodePurity)

importance <- cbind(imp_rep, imp_dem) %>% 
  cbind(., as_tibble_col(c("2-week Support", "10-week Support", "Lagged State Voteshare", "Presidential Approval", "Incumbent Party", "Annual GDP Growth", "Annual Local Unemployment", "Lagged National Voteshare"))) %>% 
  pivot_longer(!value, names_to = "model",
              values_to = "importance")



importance %>% 
  mutate(importance = scales::rescale(importance)) %>% 
  ggplot(aes(y=value, x=importance, color=model)) +
  geom_point() +
  theme_bw() +
  scale_color_manual(values = c("#0000ff", "#ff0000"),
                    breaks = c("Democrat", "Republican")) +
  labs(title = "Relative Variable Importance",
       subtitle = "Polling and lagged voteshare dominate economic indicators.",
       caption = "\nModel and graphic created by Jack Schroeder.",
       x = "Relative Importance",
       y = "Variable",
       color = "Model") +
  ggsave("../Plots/importance.png")
```

```{r undecided, echo=FALSE, cache=TRUE, message=FALSE}
# The big thing on uncertainty is that the poll number sum should converge on 100 as we get closer - show this graphically to demonstrate it is the case

# This is a small snapshot of the evidence - fewer uncertain voters 2 weeks out vs 10 weeks out

consolidated %>% 
  group_by(year, state) %>% 
  summarize(sum_2 = sum(avg_support_adjusted_2),
            sum_10 = sum(avg_support_adjusted_10)) %>% 
  mutate(which = ifelse(sum_2>sum_10, 1, 0)) %>% 
  filter(!is.na(which)) %>% 
  ungroup() %>% 
  count(which)

support_days <- read_csv("../Data/pres_pollaverages_1968-2016.csv") %>% 
  select(cycle, state, modeldate, candidate_name, pct_estimate, pct_trend_adjusted, election_date) %>% 
  rename(year = cycle) %>% 
  mutate(modeldate = as.Date(modeldate, "%m/%d/%Y"),
         election_date = as.Date(election_date, "%m/%d/%Y"),
         days_to = as.numeric(difftime(election_date, modeldate, unit="days")),
         weeks_to = difftime(election_date, modeldate, unit="weeks")) %>% 
  group_by(year, state, candidate_name, days_to, weeks_to) %>% 
  summarize(avg_support = mean(pct_trend_adjusted)) %>% 
  left_join(., names, by = c("year", "candidate_name")) %>% 
  filter(!is.na(party)) %>% 
  # Taking out 1992 because of Perot.
  filter(year != 1992) %>% 
  # Attempted to weigh national undecideds more heavily. Didn't work.
  #mutate(avg_support = case_when(state == "National" ~ avg_support * 50,
  #                               TRUE ~ avg_support)) %>% 
  group_by(year, state, days_to) %>% 
  summarize(sum_support = sum(avg_support)) %>% 
  group_by(year, days_to) %>% 
  summarize(sum_support = mean(sum_support),
            n = n())%>% 
  group_by(days_to) %>% 
  summarize(avg_supporting = mean(sum_support),
            modeldays = sum(n)) %>% 
  # modeldays counts every individual model entry (per candidate per state per cycle) on that day - we want at least 300 to make sure the model isn't acting wonky
  filter(modeldays > 300,
         days_to < 100) %>% 
  mutate(undecided = 100-avg_supporting)

support_days %>% 
  ggplot(aes(x=days_to, y=undecided)) +
  geom_point() +
  geom_smooth() +
  theme_bw() +
  labs(x = "Days to Election",
       y = "Undecided Voters (in Polling Averages)",
       title = "Number of Undecided Poll Respondents Decreases as Election Nears",
       subtitle = "Sharp decrease in last few weeks of campaigning.",
       caption = "Undecideds are voters unaligned to major-party candidates.\nThis metric is calculated for every state/national poll since 1968 for every day until election.\n1992 excluded due to substantial third-party support.\nGraphic created by Jack Schroeder.") +
  ggsave("../Plots/undecided.png",
         width=8,
         height=5)

# This is why pv2p>pv
```

```{r shytrump, echo=FALSE, cache=TRUE}

# What if Trump voters are being systematically undercounted?
# For simplicity, 4 point swing in each state poll & increase in approval

# Get rid of any possible problems with outcome variables being present in data.

shy_trump_20 <- data_20 %>% filter(party == "republican") %>% mutate(avg_support_adjusted_2 = avg_support_adjusted_2 + 2, avg_support_adjusted_10 = avg_support_adjusted_10 + 2, pres_app = pres_app + 4)
shy_trump <- as_tibble(predict(mrep, shy_trump_20))

shy_biden_20 <- data_20 %>% filter(party == "democrat") %>% mutate(avg_support_adjusted_2 = avg_support_adjusted_2 - 2, avg_support_adjusted_10 = avg_support_adjusted_10 - 2, pres_app = pres_app + 4)
shy_biden <- as_tibble(predict(mdem, shy_biden_20))

shy_states <- data_20 %>% 
  group_by(state) %>% 
  summarize(mean = mean(pres_app)) %>% 
  select(state)
shy_states$rep <- shy_trump$value
shy_states$dem <- shy_biden$value

shy_results <- shy_states %>% 
  mutate(R_pv2p = rep/(rep+dem),
         D_pv2p = dem/(rep+dem),
         winner = ifelse(R_pv2p > D_pv2p, "Trump", "Biden"),
         Guide = ifelse(R_pv2p > D_pv2p, ifelse(R_pv2p > 0.55, "Favor Trump", "Lean Trump"), ifelse(D_pv2p < 0.55, "Lean Biden", "Favor Biden")))

shy_results %>% 
  ggplot(aes(fill = Guide, state=state)) +
  geom_statebins() +
  theme_statebins() +
  scale_fill_manual(values = c("#0000ff", "#add8e6", "#ffcccb", "#ff0000"),
                    breaks = c("Favor Biden", "Lean Biden", "Lean Trump", "Favor Trump")) +
  labs(title = "'Shy Trump' Projection",
       subtitle = "Biden 279, Trump 259.",
       caption = "In this scenario, Trump gets a 4-point polling/approval boost.\nPolling boost is a 4-point swing (Trump up 2, Biden down 2).\nModel and graphic created by Jack Schroeder.") +
  ggsave("../Plots/final_shy.png")

shy_results %>% 
  left_join(., elec, by = "state") %>% 
  select(state, R_pv2p, D_pv2p, winner, Guide, `2020`) %>% 
  group_by(winner) %>% 
  tally(`2020`)
```

```{r supershytrump, echo=FALSE, cache=TRUE}

# What if Trump voters are being systematically undercounted?
# For simplicity, 4 point swing in each state poll & increase in approval

# Get rid of any possible problems with outcome variables being present in data.

super_shy_trump_20 <- data_20 %>% filter(party == "republican") %>% mutate(avg_support_adjusted_2 = avg_support_adjusted_2 + 4, avg_support_adjusted_10 = avg_support_adjusted_10 + 4, pres_app = pres_app + 8)
super_shy_trump <- as_tibble(predict(mrep, super_shy_trump_20))

super_shy_biden_20 <- data_20 %>% filter(party == "democrat") %>% mutate(avg_support_adjusted_2 = avg_support_adjusted_2 - 4, avg_support_adjusted_10 = avg_support_adjusted_10 - 4, pres_app = pres_app + 8)
super_shy_biden <- as_tibble(predict(mdem, super_shy_biden_20))

super_shy_states <- data_20 %>% 
  group_by(state) %>% 
  summarize(mean = mean(pres_app)) %>% 
  select(state)
super_shy_states$rep <- super_shy_trump$value
super_shy_states$dem <- super_shy_biden$value

super_shy_results <- super_shy_states %>% 
  mutate(R_pv2p = rep/(rep+dem),
         D_pv2p = dem/(rep+dem),
         winner = ifelse(R_pv2p > D_pv2p, "Trump", "Biden"),
         Guide = ifelse(R_pv2p > D_pv2p, ifelse(R_pv2p > 0.55, "Favor Trump", "Lean Trump"), ifelse(D_pv2p < 0.55, "Lean Biden", "Favor Biden")))

super_shy_results %>% 
  ggplot(aes(fill = Guide, state=state)) +
  geom_statebins() +
  theme_statebins() +
  scale_fill_manual(values = c("#0000ff", "#add8e6", "#ffcccb", "#ff0000"),
                    breaks = c("Favor Biden", "Lean Biden", "Lean Trump", "Favor Trump")) +
  labs(title = "'Super Shy Trump' Projection",
       subtitle = "Trump 285, Biden 253.",
       caption = "In this scenario, Trump gets a 8-point polling/approval boost.\nPolling boost is a 8-point swing (Trump up 4, Biden down 4).\nModel and graphic created by Jack Schroeder.") +
  ggsave("../Plots/final_super_shy.png")

super_shy_results %>% 
  left_join(., elec, by = "state") %>% 
  select(state, R_pv2p, D_pv2p, winner, Guide, `2020`) %>% 
  group_by(winner) %>% 
  tally(`2020`)
```

```{r fantasyworld, echo=FALSE, cache=TRUE}

# A better world for Trump - zero economic growth, 25% lower unemployment, 50% approval, six point swing in polls for all states

#mrep

fan_trump_20 <- data_20 %>% 
  filter(party == "republican") %>% 
  mutate(avg_support_adjusted_2 = avg_support_adjusted_2 + 3.25, 
         avg_support_adjusted_10 = avg_support_adjusted_10 + 3.25,
         unemployment_loc_a = .75*unemployment_loc_a,
         GDP_growth_a = 0,
         pres_app = 50)

fan_trump <- as_tibble(predict(mrep, fan_trump_20))

fan_biden_20 <- data_20 %>% 
  filter(party == "democrat") %>% 
  mutate(avg_support_adjusted_2 = avg_support_adjusted_2 - 3.25, 
         avg_support_adjusted_10 = avg_support_adjusted_10 - 3.25,
         unemployment_loc_a = .75*unemployment_loc_a,
         GDP_growth_a = 0,
         pres_app = 50)

fan_biden <- as_tibble(predict(mdem, fan_biden_20))

fan_states <- data_20 %>% 
  group_by(state) %>% 
  summarize(mean = mean(pres_app)) %>% 
  select(state)
fan_states$rep <- fan_trump$value
fan_states$dem <- fan_biden$value

fan_results <- fan_states %>% 
  mutate(R_pv2p = rep/(rep+dem),
         D_pv2p = dem/(rep+dem),
         winner = ifelse(R_pv2p > D_pv2p, "Trump", "Biden"),
         Guide = ifelse(R_pv2p > D_pv2p, ifelse(R_pv2p > 0.55, "Favor Trump", "Lean Trump"), ifelse(D_pv2p < 0.55, "Lean Biden", "Favor Biden")))

fan_results %>% 
  ggplot(aes(fill = Guide, state=state)) +
  geom_statebins() +
  theme_statebins() +
  scale_fill_manual(values = c("#0000ff", "#add8e6", "#ffcccb", "#ff0000"),
                    breaks = c("Favor Biden", "Lean Biden", "Lean Trump", "Favor Trump")) +
  labs(title = "'Corona? Schmorona!' Projection",
       subtitle = "Trump 279, Biden 259.",
       caption = "In this scenario, Trump gets a 6.5-point polling boost, a better economy, and higher approval.\nPolling boost is a 6.5-point swing (Trump up 3.25, Biden down 3.25).\nAnnual GDP growth is 0, state unemployment rates shrink by 25%, approval goes up to 50%.\nModel and graphic created by Jack Schroeder.") +
  ggsave("../Plots/final_fan.png")

fan_results %>% 
  left_join(., elec, by = "state") %>% 
  select(state, R_pv2p, D_pv2p, winner, Guide, `2020`) %>% 
  group_by(winner) %>% 
  tally(`2020`)
```

```{r pv, echo=FALSE, cache=TRUE}

# The problem here is that just going off of PV means there's room for third parties - the ghost of 1992 is a strong showing from Perot (even when )

pv_econ_d <- read_csv("../Data/model_input_local.csv") %>% 
  filter(party == "democrat") %>% 
  mutate(D_pv = D/total) %>% 
  group_by(state) %>% 
  mutate(D_pv_lag = lag(D_pv, order_by = year)) %>% 
  select(year, party, state, D_pv, D_pv_lag)

pv_econ <- read_csv("../Data/model_input_local.csv") %>% 
  filter(party == "republican") %>% 
  mutate(R_pv = R/total) %>% 
  group_by(state) %>% 
  mutate(R_pv_lag = lag(R_pv, order_by = year)) %>% 
  select(year, party, state, R_pv, R_pv_lag) %>% 
  full_join(., pv_econ_d, by = c("year", "party", "state")) %>% 
  mutate(my_pv = case_when(party == "republican" ~ R_pv*100,
                           party == "democrat" ~ D_pv*100),
         my_pv_lag = case_when(party == "republican" ~ R_pv_lag*100,
                               party == "democrat" ~ D_pv_lag*100)) %>% 
  select(year, party, state, my_pv, my_pv_lag)

pv_incumbent_d <- read_csv("../Data/popvote_1948-2016.csv") %>% 
  select(-c(candidate, pv2p)) %>% 
  filter(party == "democrat") %>% 
  mutate(my_us_pv_lag = lag(pv, order_by = year)) %>% 
  select(year, party, pv, my_us_pv_lag)
  
pv_incumbent <- read_csv("../Data/popvote_1948-2016.csv") %>% 
  select(-c(candidate, pv2p)) %>% 
  filter(party == "republican") %>% 
  mutate(my_us_pv_lag = lag(pv, order_by = year)) %>% 
  select(year, party, pv, my_us_pv_lag) %>% 
  rbind(., pv_incumbent_d) %>% 
  left_join(., pv_econ, by = c("year", "party"))

pv_model_data <- consolidated_omit %>% 
  left_join(., pv_incumbent, by = c("year", "party", "state"))

pv_votes_20 <- read_csv("../Data/popvote_bystate_1948-2016.csv") %>% 
  filter(year == 2016) %>%
  mutate(R_pv_16 = R/total,
         D_pv_16 = D/total) %>% 
  select(state, R_pv_16, D_pv_16)

pv_biden_20 <- biden_20 %>% 
  mutate(my_us_pv_lag = 51.16) %>% 
  left_join(., pv_votes_20, by = "state") %>% 
  rename(my_pv_lag = D_pv_16) %>% 
  select(-R_pv_16)

pv_trump_20 <- trump_20 %>% 
  mutate(my_us_pv_lag = 48.83) %>% 
  left_join(., pv_votes_20, by = "state") %>% 
  rename(my_pv_lag = R_pv_16) %>% 
  select(-D_pv_16)

# Then model

set.seed(07901)
pv_mrep <- train(my_pv ~ avg_support_adjusted_2 + avg_support_adjusted_10 + my_pv_lag + pres_app + incumbent_party + GDP_growth_a + unemployment_loc_a + my_us_pv_lag, pv_model_data, subset = pv_model_data$party == "republican", method = "ranger")

pv_trump <- as_tibble(predict(pv_mrep, pv_trump_20))

set.seed(07901)
pv_mdem <- train(my_pv ~ avg_support_adjusted_2 + avg_support_adjusted_10 + my_pv_lag + pres_app + incumbent_party + GDP_growth_a + unemployment_loc_a + my_us_pv_lag, pv_model_data, subset = pv_model_data$party == "democrat", method = "ranger")

pv_biden <- as_tibble(predict(pv_mdem, pv_biden_20))

pv_states <- data_20 %>% 
  group_by(state) %>% 
  summarize(mean = mean(pres_app)) %>% 
  select(state)
pv_states$rep <- pv_trump$value
pv_states$dem <- pv_biden$value

pv_results <- pv_states %>% 
  mutate(R_pv2p = rep/(rep+dem),
         D_pv2p = dem/(rep+dem),
         winner = ifelse(R_pv2p > D_pv2p, "Trump", "Biden"),
         Guide = ifelse(rep > dem, ifelse(rep-dem > 10, "Favor Trump", "Lean Trump"), ifelse(dem-rep < 10, "Lean Biden", "Favor Biden")),
         p3 = 100-rep-dem)

# Third party vote is WAY too high

pv_results %>% 
  ggplot(aes(fill = Guide, state=state)) +
  geom_statebins() +
  theme_statebins() +
  scale_fill_manual(values = c("#0000ff", "#add8e6", "#ffcccb", "#ff0000"),
                    breaks = c("Favor Biden", "Lean Biden", "Lean Trump", "Favor Trump")) +
  labs(title = "Alternate RF Projection",
       subtitle = "Biden 412, Trump 126.",
       caption = "This model performs random forest regression using unscaled popular vote totals (instead of two-party shares).\nThis model scored worse on selected evaluations.\nModel and graphic created by Jack Schroeder.") +
  ggsave("../Plots/final_pv.png")

pv_results %>% 
  left_join(., elec, by = "state") %>% 
  select(state, R_pv2p, D_pv2p, winner, Guide, `2020`) %>% 
  group_by(winner) %>% 
  tally(`2020`)

```

```{r 2016 error, echo=FALSE, cache=TRUE}

# If polls in swing states aren't uniformly off but instead off by specific 2016 errors.
# Will also increase pres. approval by mean of these errors.
# Error is a swing between both candidates.

error_trump_20 <- data_20 %>% 
  filter(party == "republican") %>% 
  mutate(avg_support_adjusted_2 = case_when(state == "Arizona" ~ avg_support_adjusted_2 + 0.6,
                                            state == "Colorado" ~ avg_support_adjusted_2 - 0.55,
                                            state == "Florida" ~ avg_support_adjusted_2 + 0.85,
                                            state == "Georgia" ~ avg_support_adjusted_2 + 0.55,
                                            state == "Iowa" ~ avg_support_adjusted_2 + 3,
                                            state == "Maine" ~ avg_support_adjusted_2 + 4.95,
                                            state == "Michigan" ~ avg_support_adjusted_2 + 2.1,
                                            state == "Minnesota" ~ avg_support_adjusted_2 + 2.2,
                                            state == "Nevada" ~ avg_support_adjusted_2 - 0.85,
                                            state == "New Hampshire" ~ avg_support_adjusted_2 + 1.5,
                                            state == "New Mexico" ~ avg_support_adjusted_2 - 1.45,
                                            state == "North Carolina" ~ avg_support_adjusted_2 + 2.2,
                                            state == "Ohio" ~ avg_support_adjusted_2 + 3.05,
                                            state == "Pennsylvania" ~ avg_support_adjusted_2 + 2.2,
                                            state == "Texas" ~ avg_support_adjusted_2 + 0.25,
                                            state == "Virginia" ~ avg_support_adjusted_2 + 0.05,
                                            state == "Wisconsin" ~ avg_support_adjusted_2 + 3.1,
                                            TRUE ~ avg_support_adjusted_2),
         avg_support_adjusted_10 = case_when(state == "Arizona" ~ avg_support_adjusted_10 + 0.6,
                                            state == "Colorado" ~ avg_support_adjusted_10 - 0.55,
                                            state == "Florida" ~ avg_support_adjusted_10 + 0.85,
                                            state == "Georgia" ~ avg_support_adjusted_10 + 0.55,
                                            state == "Iowa" ~ avg_support_adjusted_10 + 3,
                                            state == "Maine" ~ avg_support_adjusted_10 + 4.95,
                                            state == "Michigan" ~ avg_support_adjusted_10 + 2.1,
                                            state == "Minnesota" ~ avg_support_adjusted_10 + 2.2,
                                            state == "Nevada" ~ avg_support_adjusted_10 - 0.85,
                                            state == "New Hampshire" ~ avg_support_adjusted_10 + 1.5,
                                            state == "New Mexico" ~ avg_support_adjusted_10 - 1.45,
                                            state == "North Carolina" ~ avg_support_adjusted_10 + 2.2,
                                            state == "Ohio" ~ avg_support_adjusted_10 + 3.05,
                                            state == "Pennsylvania" ~ avg_support_adjusted_10 + 2.2,
                                            state == "Texas" ~ avg_support_adjusted_10 + 0.25,
                                            state == "Virginia" ~ avg_support_adjusted_10 + 0.05,
                                            state == "Wisconsin" ~ avg_support_adjusted_10 + 3.1,
                                            TRUE ~ avg_support_adjusted_10),
         pres_app = pres_app + 2)

error_trump <- as_tibble(predict(mrep, error_trump_20))

error_biden_20 <- data_20 %>% 
  filter(party == "democrat") %>% 
  mutate(avg_support_adjusted_2 = case_when(state == "Arizona" ~ avg_support_adjusted_2 - 0.6,
                                            state == "Colorado" ~ avg_support_adjusted_2 + 0.55,
                                            state == "Florida" ~ avg_support_adjusted_2 - 0.85,
                                            state == "Georgia" ~ avg_support_adjusted_2 - 0.55,
                                            state == "Iowa" ~ avg_support_adjusted_2 - 3,
                                            state == "Maine" ~ avg_support_adjusted_2 - 4.95,
                                            state == "Michigan" ~ avg_support_adjusted_2 - 2.1,
                                            state == "Minnesota" ~ avg_support_adjusted_2 - 2.2,
                                            state == "Nevada" ~ avg_support_adjusted_2 + 0.85,
                                            state == "New Hampshire" ~ avg_support_adjusted_2 - 1.5,
                                            state == "New Mexico" ~ avg_support_adjusted_2 + 1.45,
                                            state == "North Carolina" ~ avg_support_adjusted_2 - 2.2,
                                            state == "Ohio" ~ avg_support_adjusted_2 - 3.05,
                                            state == "Pennsylvania" ~ avg_support_adjusted_2 - 2.2,
                                            state == "Texas" ~ avg_support_adjusted_2 - 0.25,
                                            state == "Virginia" ~ avg_support_adjusted_2 - 0.05,
                                            state == "Wisconsin" ~ avg_support_adjusted_2 - 3.1,
                                            TRUE ~ avg_support_adjusted_2),
         avg_support_adjusted_10 = case_when(state == "Arizona" ~ avg_support_adjusted_10 - 0.6,
                                            state == "Colorado" ~ avg_support_adjusted_10 + 0.55,
                                            state == "Florida" ~ avg_support_adjusted_10 - 0.85,
                                            state == "Georgia" ~ avg_support_adjusted_10 - 0.55,
                                            state == "Iowa" ~ avg_support_adjusted_10 - 3,
                                            state == "Maine" ~ avg_support_adjusted_10 - 4.95,
                                            state == "Michigan" ~ avg_support_adjusted_10 - 2.1,
                                            state == "Minnesota" ~ avg_support_adjusted_10 - 2.2,
                                            state == "Nevada" ~ avg_support_adjusted_10 + 0.85,
                                            state == "New Hampshire" ~ avg_support_adjusted_10 - 1.5,
                                            state == "New Mexico" ~ avg_support_adjusted_10 + 1.45,
                                            state == "North Carolina" ~ avg_support_adjusted_10 - 2.2,
                                            state == "Ohio" ~ avg_support_adjusted_10 - 3.05,
                                            state == "Pennsylvania" ~ avg_support_adjusted_10 - 2.2,
                                            state == "Texas" ~ avg_support_adjusted_10 - 0.25,
                                            state == "Virginia" ~ avg_support_adjusted_10 - 0.05,
                                            state == "Wisconsin" ~ avg_support_adjusted_10 - 3.1,
                                            TRUE ~ avg_support_adjusted_10),
         pres_app = pres_app - 2)

error_biden <- as_tibble(predict(mdem, error_biden_20))

error_states <- data_20 %>% 
  group_by(state) %>% 
  summarize(mean = mean(pres_app)) %>% 
  select(state)
error_states$rep <- error_trump$value
error_states$dem <- error_biden$value

error_results <- error_states %>% 
  mutate(R_pv2p = rep/(rep+dem),
         D_pv2p = dem/(rep+dem),
         winner = ifelse(R_pv2p > D_pv2p, "Trump", "Biden"),
         Guide = ifelse(R_pv2p > D_pv2p, ifelse(R_pv2p > 0.55, "Favor Trump", "Lean Trump"), ifelse(D_pv2p < 0.55, "Lean Biden", "Favor Biden")))

error_results %>% 
  ggplot(aes(fill = Guide, state=state)) +
  geom_statebins() +
  theme_statebins() +
  scale_fill_manual(values = c("#0000ff", "#add8e6", "#ffcccb", "#ff0000"),
                    breaks = c("Favor Biden", "Lean Biden", "Lean Trump", "Favor Trump")) +
  labs(title = "'Error Trump' Projection",
       subtitle = "Biden 319, Trump 219.",
       caption = "In this scenario, polling errors in key states equals their errors in 2016.\nThe 2016 error is split evenly between both candidates.\nModel and graphic created by Jack Schroeder.") +
  ggsave("../Plots/final_error.png")

error_results %>% 
  left_join(., elec, by = "state") %>% 
  select(state, R_pv2p, D_pv2p, winner, Guide, `2020`) %>% 
  group_by(winner) %>% 
  tally(`2020`)

```

```{r incumbency, echo=FALSE, cache=TRUE}
# Then create an incumbency model instead of a dem/rep model.

# Get rid of any possible problems with outcome variables being present in data.

inc_model_data <- consolidated_omit %>% 
  select(-c(winner, pv2p, total, D, R, R_pv2p, D_pv2p, D_pv, R_pv, VEP, VAP))

set.seed(07901)
minc <- train(my_pv2p ~ avg_support_adjusted_2 + avg_support_adjusted_10 + my_pv2p_lag + pres_app + incumbent + GDP_growth_a + unemployment_loc_a + my_us_pv2p_lag, model_data, subset = inc_model_data$incumbent_party == TRUE, method = "ranger")

trump_20 <- data_20 %>% filter(party == "republican")
inc_trump <- as_tibble(predict(minc, trump_20))

set.seed(07901)
mchal <- train(my_pv2p ~ avg_support_adjusted_2 + avg_support_adjusted_10 + my_pv2p_lag + pres_app + incumbent + GDP_growth_a + unemployment_loc_a + my_us_pv2p_lag, model_data, subset = inc_model_data$incumbent_party == FALSE, method = "ranger")

biden_20 <- data_20 %>% filter(party == "democrat")
inc_biden <- as_tibble(predict(mchal, biden_20))

inc_states <- data_20 %>% 
  group_by(state) %>% 
  summarize(mean = mean(pres_app)) %>% 
  select(state)
inc_states$rep <- inc_trump$value
inc_states$dem <- inc_biden$value

inc_results <- inc_states %>% 
  mutate(R_pv2p = rep/(rep+dem),
         D_pv2p = dem/(rep+dem),
         winner = ifelse(R_pv2p > D_pv2p, "Trump", "Biden"),
         Guide = ifelse(R_pv2p > D_pv2p, ifelse(R_pv2p > 0.55, "Favor Trump", "Lean Trump"), ifelse(D_pv2p < 0.55, "Lean Biden", "Favor Biden")))

inc_results %>% 
  ggplot(aes(fill = Guide, state=state)) +
  geom_statebins() +
  theme_statebins() +
  scale_fill_manual(values = c("#0000ff", "#add8e6", "#ffcccb", "#ff0000"),
                    breaks = c("Favor Biden", "Lean Biden", "Lean Trump", "Favor Trump")) +
  labs(title = "2020 Election Projection",
       subtitle = "Biden 350, Trump 188",
       caption = "This is a random forest model based on incumbency.\nThe main model separates by party.\nModel and graphic created by Jack Schroeder.") +
  ggsave("../Plots/final_inc.png")

# EC tally

inc_results %>% 
  left_join(., elec, by = "state") %>% 
  select(state, R_pv2p, D_pv2p, winner, Guide, `2020`) %>% 
  group_by(winner) %>% 
  tally(`2020`)
```

```{r unitary, echo=FALSE, cache=TRUE}
# Then a unitary model?

uni_model_data <- consolidated_omit %>% 
  select(-c(winner, pv2p, total, D, R, R_pv2p, D_pv2p, D_pv, R_pv, VEP, VAP))

set.seed(07901)
muni <- train(my_pv2p ~ avg_support_adjusted_2 + avg_support_adjusted_10 + my_pv2p_lag + pres_app + incumbent_party + GDP_growth_a + unemployment_loc_a + my_us_pv2p_lag, model_data, method = "ranger")

uni_trump <- as_tibble(predict(muni, trump_20))
uni_biden <- as_tibble(predict(muni, biden_20))

uni_states <- data_20 %>% 
  group_by(state) %>% 
  summarize(mean = mean(pres_app)) %>% 
  select(state)
uni_states$rep <- uni_trump$value
uni_states$dem <- uni_biden$value

uni_results <- uni_states %>% 
  mutate(R_pv2p = rep/(rep+dem),
         D_pv2p = dem/(rep+dem),
         winner = ifelse(R_pv2p > D_pv2p, "Trump", "Biden"),
         Guide = ifelse(R_pv2p > D_pv2p, ifelse(R_pv2p > 0.55, "Favor Trump", "Lean Trump"), ifelse(D_pv2p < 0.55, "Lean Biden", "Favor Biden")))

uni_results %>% 
  ggplot(aes(fill = Guide, state=state)) +
  geom_statebins() +
  theme_statebins() +
  scale_fill_manual(values = c("#0000ff", "#add8e6", "#ffcccb", "#ff0000"),
                    breaks = c("Favor Biden", "Lean Biden", "Lean Trump", "Favor Trump")) +
  labs(title = "2020 Election Projection",
       subtitle = "Biden 350, Trump 188",
       caption = "This is a random forest model based on incumbency.\nThe main model separates by party.\nModel and graphic created by Jack Schroeder.") +
  ggsave("../Plots/final_uni.png")

# EC tally

uni_results %>% 
  left_join(., elec, by = "state") %>% 
  select(state, R_pv2p, D_pv2p, winner, Guide, `2020`) %>% 
  group_by(winner) %>% 
  tally(`2020`)

muni$bestTune
muni$yLimits
mdem$yLimits
mrep$yLimits
mdem$bestTune
mdem$results

muni_rf <- randomForest(my_pv2p ~ avg_support_adjusted_2 + avg_support_adjusted_10 + my_pv2p_lag + pres_app + incumbent_party + GDP_growth_a + unemployment_loc_a + my_us_pv2p_lag, model_data)

pred_muni <- predict(muni_rf, biden_20, predict.all=TRUE)
```

```{r votes, echo=FALSE, cache=TRUE}

raw_model_data <- consolidated_omit %>% 
  select(-c(winner, pv2p, total, R_pv2p, D_pv2p, D_pv, R_pv, VAP))

set.seed(07901)
raw_mrep <- train(R ~ avg_support_adjusted_2 + avg_support_adjusted_10 + my_pv2p_lag + pres_app + incumbent_party + GDP_growth_a + unemployment_loc_a + my_us_pv2p_lag + VEP, raw_model_data, subset = raw_model_data$party == "republican", method = "ranger")

raw_mrep

raw_trump <- as_tibble(predict(raw_mrep, trump_20))

set.seed(07901)
raw_mdem <- train(D ~ avg_support_adjusted_2 + avg_support_adjusted_10 + my_pv2p_lag + pres_app + incumbent_party + GDP_growth_a + unemployment_loc_a + my_us_pv2p_lag + VEP, raw_model_data, subset = raw_model_data$party == "democrat", method = "ranger")

raw_biden <- as_tibble(predict(raw_mdem, biden_20))

raw_states <- data_20 %>% 
  group_by(state) %>% 
  summarize(mean = mean(pres_app)) %>% 
  select(state)
raw_states$rep <- raw_trump$value
raw_states$dem <- raw_biden$value

raw_results <- raw_states %>% 
  mutate(R_pv2p = rep/(rep+dem),
         D_pv2p = dem/(rep+dem),
         winner = ifelse(R_pv2p > D_pv2p, "Trump", "Biden"),
         Guide = ifelse(R_pv2p > D_pv2p, ifelse(R_pv2p > 0.55, "Favor Trump", "Lean Trump"), ifelse(D_pv2p < 0.55, "Lean Biden", "Favor Biden")))

raw_results %>% 
  ggplot(aes(fill = Guide, state=state)) +
  geom_statebins() +
  theme_statebins() +
  scale_fill_manual(values = c("#0000ff", "#add8e6", "#ffcccb", "#ff0000"),
                    breaks = c("Favor Biden", "Lean Biden", "Lean Trump", "Favor Trump")) +
  labs(title = "2020 Election Projection (Raw)",
       subtitle = "Biden 334, Trump 204.",
       caption = "The underlying model is a random forest regression that includes various economic/polling indicators.\nRandom forests utilize decision trees with some predictors on some of the data to avoid overfitting.\nThe best of these trees are used together to predict future outcomes.\nModel and graphic created by Jack Schroeder.") +
  ggsave("../Plots/final_raw.png")

# EC tally

results %>% 
  left_join(., elec, by = "state") %>% 
  select(state, R_pv2p, D_pv2p, winner, Guide, `2020`) %>% 
  group_by(winner) %>% 
  tally(`2020`)

raw_mdem
raw_mrep
```


```{r}
# Model comps
`wOriginal Model` <- round(rmse_final_model, 3)
`wFinal Model (R)` <- 3.138
`wFinal Model (D)` <- 2.909
`wRF PV (D)` <- 2.908
`wRF PV (R)` <- 2.804
`wIncumbent (R)` <- 3.222
`wIncumbent (D)` <- 3.407
`wUnitary RF` <- 3.101
`w Raw (R)` <- 1.14
`w Raw (D)` <- 2.14
                          

raw_rmse <- data.frame(Model = "Raw Votes (R)", RMSE = "177k votes")
raw_rmse2 <- data.frame(Model = "Raw Votes (D)", RMSE = "208k votes")

rmse_tbl <- data.frame(`wOriginal Model`, `wFinal Model (R)`, `wFinal Model (D)`, `wRF PV (D)`, `wRF PV (R)`, `wIncumbent (R)`, `wIncumbent (D)`, `wUnitary RF`) %>% 
  pivot_longer(cols = starts_with("w"),
    names_to = "Model",
               values_to = "RMSE") %>% 
  mutate(Model = case_when(Model == "wOriginal.Model" ~ "Original",
                           Model == "wFinal.Model..R." ~ "Two-Party (R)",
                           Model == "wFinal.Model..D." ~ "Two-Party (D)",
                           Model == "wRF.PV..D." ~ "Unscaled (R)",
                           Model == "wRF.PV..R." ~ "Unscaled (D)",
                           Model == "wIncumbent..R." ~ "Incumbent (R)",
                           Model == "wIncumbent..D." ~ "Incumbent (D)",
                           Model == "wUnitary.RF" ~ "Unitary")) %>% 
  rbind(., raw_rmse) %>% 
  rbind(., raw_rmse2) %>% 
  gt() %>% 
  tab_header(title = "Evaluating Model Error",
             subtitle = "All Random Forest Models Beat Original Model") %>% 
  tab_source_note(source_note = c("RMSE in % points of state vote totals unless noted.", "Models and graphic created by Jack Schroeder.")) %>% 
  gtsave("../Plots/rmse.png")

```

